 # What is NumPy?
 NumPy (Numerical Python) is an open-source Python library used for numerical computing.
 It provides support for large multidimensional arrays and matrices, along with a collection of
 high-level mathematical functions to operate on these arrays.

#  Why Use NumPy?
 1.Efficient memory storage and performance
 
 2.Broad range of mathematical, logical, shape manipulation, sorting, selecting, I/O, and linear algebra functions
 
 3.Foundation for most Python data science libraries (e.g., Pandas, Scikit-learn)

In [1]:
import numpy as np
a=([1,2,3,4])
b=np.array(a)
max_number=np.max(b)
print(max_number)

4


In [2]:
b

array([1, 2, 3, 4])

In [3]:
a

[1, 2, 3, 4]

In [4]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [5]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [6]:
np.linspace(0,1,2, dtype=int)

array([0, 1])

In [7]:
np.linspace(0,1,3, dtype=int)

array([0, 0, 1])

 Que:1. Create a 1D NumPy array of numbers from 0 to 9

In [8]:
#Que:1. Create a 1D NumPy array of numbers from 0 to 9
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 2. Create a 3×3 array filled with zeros

In [9]:
#que 2: 2. Create a 3×3 array filled with zeros
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr=np.ones((3,3),dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Que 3: Create a 3×3 identity matrix

In [12]:
#que 3: Create a 3×3 identity matrix
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Que 4:Create a 5×5 matrix with values from 1 to 25

In [13]:
#Que 4:Create a 5×5 matrix with values from 1 to 25
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Que 5: Convert a list to a NumPy array

In [14]:
#Que 5: Convert a list to a NumPy array
list([1,2,3,4,5,6,7])
arr=np.array(list)
arr

array(<class 'list'>, dtype=object)

In [15]:
list=([1,2,3,4,5,6,7])
arr=np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


In [17]:
# For 2D array
my_list_2d = [[1, 2], [3, 4]]
arr_2d = np.array(my_list_2d)
print(arr_2d)

[[1 2]
 [3 4]]


Que 6: Replace all odd numbers in a NumPy array with -1

In [18]:
# Que 6: Replace all odd numbers in a NumPy array with -1
arr= np.arange(10)
arr[arr % 2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
arr = np.arange(10,20)
arr[arr % 2==1] = -5
arr

array([10, -5, 12, -5, 14, -5, 16, -5, 18, -5])

Replace all even numbers in a NumPy array with -7

In [20]:
# Replace all even numbers in a NumPy array with -7
arr = np.arange(10,20)
arr[arr % 2==0] = -7
arr

array([-7, 11, -7, 13, -7, 15, -7, 17, -7, 19])

 8. Find the maximum and minimum of a NumPy array

In [21]:
arr = np.array([2,6,22,77,72])
min_num = np.min(arr)
max_num =np.max(arr)
print(min_num)
print(max_num)

2
77


In [22]:
 To normalize a NumPy array (scale values between 0 and 1), you use the Min-Max normalization formula:
normalized_value =(𝑥−min(𝑥))/(max(𝑥)−min(𝑥))

🧠 Meaning:
Normalization is used to scale data within a fixed range (usually 0 to 1) to make it easier to compare values and improve the performance of algorithms (especially in machine learning and image processing).
It preserves the distribution of the data but changes the scale.

SyntaxError: invalid character '−' (U+2212) (3274427947.py, line 2)

9. Normalize a NumPy array (scale between 0 and 1)

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
# Min-Max Normalization
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print("Original:", arr)
print("Normalized:", normalized_arr)

In [ ]:
#Que 9 :Normalize a NumPy array (scale between 0 and 1)
arr = np.array([1,2,3,4,5])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

10. Get the common elements between two NumPy arrays

In [ ]:
#Que 10:Get the common elements between two NumPy arrays
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
print(np.intersect1d(a,b))

 11. Create a 10x10 array with random values and find the mean of each row

In [ ]:
#Que 11:Create a 10x10 array with random values and find the mean of each row 
arr = np.random.rand(10 , 10)
row_mean = arr.mean(axis =1)
print(row_mean)

In [ ]:
#Que : write a code using numpy function to multiply both array.
a=np.array([2,3,4])
b=np.array([2,3,4])
print(np.dot(a,b))

12. Reverse a NumPy array

In [ ]:
#Que 12: Reverse a NumPy array
arr = np.array([1,2,3,4])
print(arr[::-1])

13. Find the position of the maximum element in a 2D array

In [ ]:
#Que 13:Find the position of the maximum element in a 2D array
arr = np.random.randint(1,100,(3,3))
print(arr)
print(np.argmax(arr))
print(np.unravel_index(np.argmax(arr),arr.shape))

In [ ]:
arr = np.random.randint(1,100,(3,3))
print(np.argmax(arr))
print(np.unravel_index(np.argmax(arr),arr.shape))

In [ ]:
arr = np.random.randint(1,100,(3,3))
print(arr)
print(np.argmax(arr))

In [ ]:
arr = np.random.randint(1,100,(3,3))
print(arr)
print(np.unravel_index(np.argmax(arr),arr.shape))

In [ ]:
arr = np.random.randint(1,100,(3,3))
print(arr)
print(np.unravel_index(np.argmin(arr),arr.shape))

In [ ]:
arr = np.random.randint(1,100,(3,3))
print(arr)
print(np.argmin(arr))

14. Replace NaN values with zero

In [ ]:
# Que 14:Replace NaN values with zero (Here NaN stand for Not-a-Number)
arr = np.array([1,2,np.nan,4])
arr = np.nan_to_num(arr)
print(arr)

In [ ]:
arr = np.array([1,2,np.nan,4])
arr = np.nan_to_num(arr, nan=-1)
print(arr)

15. Flatten a multi-dimensional array

In [ ]:
#Que 15:Flatten a multi-dimensional array
arr=np.array([[1,2],[3,4]])
print("Original array:\n",arr)
flat=arr.flatten()
print(flat)

16. Create a checkerboard pattern (8x8)

In [ ]:
#Que 16:Create a checkerboard pattern (8x8)
arr = np.zeros((8,8))
arr[1::2 , ::2] = 1
arr[::2 , 1::2] = 1
print(arr)

In [ ]:
"""arr[1::2, ::2] = 1
Selects rows starting from index 1 with step 2 → rows: 1, 3, 5, 7
In those rows, selects columns starting from 0 with step 2 → cols: 0, 2, 4, 6
Sets those positions to 1"""

arr = np.zeros((8,8),dtype=int)
arr[1::2 , ::2] = 1
arr[::2 , 1::2] = 1
print(arr)

17. Create a 100x100 matrix and compute the sum of all values

In [ ]:
#Que 17:Create a 100x100 matrix and compute the sum of all values
import numpy as np
arr = np.random.rand(100, 100)
print('Original array:\n', arr)
total = np.sum(arr)
print("Total sum =", total)

18. Extract all numbers between 30 and 70 in a NumPy array

In [ ]:
# Que 18: Extract all numbers between 30 and 70 in a NumPy array
arr = np.arange(100)
print(arr[(arr > 30) & (arr <70)])

19. Convert a float array to integer without roundin

In [ ]:
#Que 19:Convert a float array to integer without roundin
arr = np.array([1.5 , 2.3 , 3.9])
print(arr.astype(int))

 20. Stack two arrays vertically and horizontally

In [ ]:
#Que 20:Stack two arrays vertically and horizontally
a = np.array([[1,2] , [3,4]])
b = np.array([[5,6] , [7,8]])
print(np.vstack((a , b)))
print(np.hstack((a,b)))

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
vstack = np.vstack((a, b))
hstack = np.hstack((a, b))
print("Vertical:\n", vstack)
print("Horizontal:\n", hstack)

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# Vertical stacking
print("Vertical Array:")
print(np.vstack((a, b)))
# Horizontal stacking
print("Horizontal Array:")
print(np.hstack((a, b)))

21. How to reshape a 1D array to 3x3?

In [ ]:
#21. How to reshape a 1D array to 3x3?
arr = np.arange(9)
print('Array:',arr)
reshaped = arr.reshape(3, 3)
print(reshaped)

22.What is broadcasting in NumPy?

In [ ]:
#22.What is broadcasting in NumPy?
a = np.array([1, 2, 3])
b = 2
result = a * b
print(result)

23. How to perform element-wise operations on two arrays?

In [ ]:
# 23.How to perform element-wise operations on two arrays?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(a-b)
print(a/b)
print(a//b)
print(a%b)

24. How to find the mean, median, std deviation of an array?

In [ ]:
# 24. How to find the mean, median, std deviation of an array?
arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))

25. How to find the index of maximum and minimum element?

In [ ]:
# 25. How to find the index of maximum and minimum element?
arr = np.array([10, 20, 5, 30])
print("Max index:", np.argmax(arr))
print("Min index:", np.argmin(arr))

26. How to filter elements less than 10 in an array?

In [ ]:
# 26.How to filter elements less than 10 in an array?
arr = np.array([5, 12, 18, 7, 3])
filtered = arr[arr < 10]
print(filtered)

27. How to get unique values from an array?

In [ ]:
# 27. How to get unique values from an array?
arr=([1,22,3,3,4,4,5,6,6,7])
print(arr)
unique=np.unique(arr)
print(unique)

In [ ]:
arr=([1,22,3,3,4,4,5,6,6,7])
print(np.unique(arr))

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
print(np.unique(arr))

# What is Dot Product?
The dot product is a specific kind of multiplication between two arrays (vectors or matrices):

For vectors, it gives a single number.

For matrices, it gives another matrix as result (matrix multiplication)

28. How to compute dot product of two arrays?

In [ ]:
# 28. How to compute dot product of two arrays?
import numpy as np
a = np.array([1, 2, 3])     #1×4+2×5+3×6=4+10+18=32
b = np.array([4, 5, 6])
result = np.dot(a, b)  # OR a @ b
print("Dot Product:", result)

In [24]:
# Define two 2x2 matrices
A = np.array([[1, 2],       #Row1⋅Col1=1×5+2×7=19,1×6+2×8=22
              [3, 4]])      #Row2⋅Col1=3×5+4×7=43,3×6+4×8=50

B = np.array([[5, 6],
              [7, 8]])

# Compute the matrix dot product
result = np.dot(A, B)  # OR A @ B

# Print the result
print("Matrix Dot Product:\n", result)

Matrix Dot Product:
 [[19 22]
 [43 50]]


In [23]:
a = np.array([1, 2])
b = np.array([3, 4])
dot = np.dot(a, b)
print(dot)

11


#  What is Broadcasting? 
Broadcasting lets NumPy automatically expand arrays of different shapes so operations (like addition or multiplication) can still happen element-wise.

In [25]:
a = np.array([1, 2, 3])
b = 5  # scalar
print("a + b =", a + b)

a + b = [6 7 8]


In [30]:
a = np.array([1, 2, 3])
b = 10
print(a * b)

[10 20 30]


In [26]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])
print("A + B:\n", A + B)

A + B:
 [[11 22 33]
 [14 25 36]]


In [31]:
#2D Array × 1D Array (Row-wise)
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])
print(A * B)

[[ 10  40  90]
 [ 40 100 180]]


In [32]:
# 2D Array × Column Vector (Column-wise)
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[10],
              [20]])
print(A * B)

[[ 10  20  30]
 [ 80 100 120]]


29. How to solve a system of linear equations?

In [28]:
#29. How to solve a system of linear equations?
"""
2x + y = 5  
x + 3y = 6

Ans:-
Step 1: Solve one equation for one variable
From Equation (2):
x=6−3y

Step 2: Substitute into the other equation
Put into Equation (1):
2(6−3y)+y=5
12−6y+y=5
12−5y=5
−5y=5−12=−7⇒y= 5/7 =1.4

Step 3: Back-substitute to find x
x=6−3(1.4)=6−4.2=1.8
"""

import numpy as np
# Coefficients
A = np.array([[2, 1],
              [1, 3]])
# Constants on the right-hand side
B = np.array([5, 6])
# Solve for x
x = np.linalg.solve(A, B)
print("Solution:", x)

Solution: [1.8 1.4]


30. How to invert a matrix?

In [33]:
#30. How to invert a matrix?
mat = np.array([[1, 2], [3, 4]])
inv = np.linalg.inv(mat)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


31. How to save and load a NumPy array to/from a file?

In [35]:
# 31. How to save and load a NumPy array to/from a file?
arr = np.array([1, 2, 3, 4, 5])
np.save('my_array.npy', arr)

loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[1 2 3 4 5]
