# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating Array

In [4]:
mylist = [0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [5]:
type(mylist)

list

In [7]:
arr = np.array(mylist)  # Converting the list into the array form
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)  # Array type

numpy.ndarray

In [10]:
type(mylist)

list

In [11]:
np. # we learn important function

SyntaxError: invalid syntax (3980787790.py, line 1)

In [13]:
np.arange(15) #It will arrange the array from 0 to 15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(7.0)   # Arrange the array in float value

array([0., 1., 2., 3., 4., 5., 6.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,5)  

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,22)  #Arange the array from 10 to n-1 i.e 21

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [18]:
np.arange(20,10)  # 1st argument must be grater than 2nd argument

array([], dtype=int32)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(-22,-7)

array([-22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,
        -9,  -8])

In [21]:
np.arange(10,10)

array([], dtype=int32)

In [22]:
np.arange()

TypeError: arange() requires stop to be specified.

In [23]:
np.arange(10,30,3)  # starting index = 10, end index = 30, step index = 3

array([10, 13, 16, 19, 22, 25, 28])

In [24]:
np.arange(0,10,5)

array([0, 5])

In [25]:
np.arange(10,30,3,4)   

TypeError: Cannot interpret '4' as a data type

In [28]:
# ZEROS METHOD
np.zeros(3)   # Parameter tunning -- reverse the parameter given by the system

array([0., 0., 0.])

In [29]:
np.zeros(5, dtype=int)  #hyperparameter tunning --- user change   ....All thye zeros are in the integers

array([0, 0, 0, 0, 0])

In [31]:
np.zeros((2,3), dtype=int)   # by default 1st argument is rows and 2nd argument is columns  

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
zero = np.zeros([2,3])
print(zero)
print(type(zero))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [33]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [35]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [37]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))   # Parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [39]:
print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [40]:
n

(6, 7)

In [41]:
n1

(6, 8)

In [42]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones(7,dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [45]:
n

(6, 7)

In [46]:
print(np.ones(n))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [47]:
print(np.ones(n,dtype=int))

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [48]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [50]:
np.twos((3,4))   # Module numpy has no atribute two... 

AttributeError: module 'numpy' has no attribute 'twos'

In [54]:
np.three(8)   #module 'numpy' has no attribute 'three'

AttributeError: module 'numpy' has no attribute 'three'

In [51]:
np.ones(2)

array([1., 1.])

In [52]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [55]:
range(7)

range(0, 7)

In [57]:
r = range(7)
r

range(0, 7)

In [62]:
type(r)

range

In [61]:
for i in r:     # it will print the value from 0 to 6
    print(i) 

0
1
2
3
4
5
6


In [64]:
list(range(7))  # It will give the range in list form

[0, 1, 2, 3, 4, 5, 6]

In [65]:
range(1,10)

range(1, 10)

In [66]:
list(range(1,10))   #Start from 1 and end wit n-1 i.e 9

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
list(range(1,10,2))  # start from 1 and end with n-1 i.e 9 and it will step 2 step

[1, 3, 5, 7, 9]

In [69]:
x = list(range(7,22))
print(x)

[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


In [70]:
rand(3,4)

NameError: name 'rand' is not defined

In [71]:
rand(3,4)
random.rand(3,4)

NameError: name 'rand' is not defined

In [72]:
np.random.rand(7)   #1D Array
                   #np.random.rand() is a NumPy function used to generate random numbers.
                  #np.random.rand() generates random floating-point numbers between 0 and 1 (including 0 but excluding 1) from a uniform distribution

array([0.64958515, 0.70934201, 0.5941907 , 0.6360793 , 0.63101937,
       0.81312366, 0.20593678])

In [73]:
np.rand(6)

AttributeError: module 'numpy' has no attribute 'rand'

In [77]:
np.random.rand(2,4)    #2D array

array([[0.1830531 , 0.96897798, 0.38806415, 0.77122457],
       [0.33361856, 0.53222161, 0.46546078, 0.36660843]])

In [78]:
np.random.randint(2,7)  # np.random.randint() is a NumPy function used to generate random integers.
                        # It returns random integers from a specified range

5

In [79]:
print(np.random.randint(10, 50, size=5))   # It will return Random 5 integer between 10 and 50-----1D Array

[13 32 34 25 42]


In [84]:
print(np.random.randint(0, 100, size=(3, 4)))   # 2D Array

[[68 20 46 46]
 [18  9 45 37]
 [76 69 20 30]]


In [85]:
np.random.randint(7,22,2)  

array([14, 20])

In [86]:
np.random.randint(7,22,8)

array([ 8, 14, 14,  9,  7, 10, 20, 10])

In [87]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [88]:
np.random.randint(-30,20,10) 

array([  4, -17,  12,   3, -17,  19,   4,  10,  -6,   8])

In [90]:
np.random.randint(20,30,10)

array([26, 23, 22, 29, 23, 23, 21, 24, 23, 21])

In [91]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

7

In [92]:
np.random.randint(10,21,7)  # Here we will get 7 random element between 10 and 21

array([16, 16, 19, 13, 18, 10, 20])

In [93]:
"""Random elements start from the 10 and goes upto 39 &
shape of the sixze is 10*10 matrix

 Generates a 10×10 matrix
 Each element is a random integer between 10 and 39
 """

np.random.randint(10,40,(10,10)) #generet the element 10 to 39 with 10*10 mtrix

array([[21, 39, 27, 36, 19, 15, 38, 11, 20, 26],
       [31, 23, 26, 28, 26, 14, 26, 24, 21, 25],
       [22, 22, 22, 21, 35, 15, 32, 24, 23, 38],
       [33, 37, 23, 17, 34, 33, 25, 24, 17, 16],
       [15, 24, 22, 39, 28, 34, 12, 34, 17, 18],
       [32, 38, 33, 14, 15, 19, 10, 22, 15, 11],
       [28, 17, 30, 27, 16, 22, 22, 31, 33, 37],
       [17, 35, 16, 32, 23, 28, 12, 32, 38, 25],
       [27, 28, 21, 30, 25, 25, 25, 24, 26, 33],
       [32, 25, 31, 26, 20, 30, 39, 29, 22, 22]])

In [94]:
np.random.randint(1,100,(7,8))  # Random integer between 1 to 99 and 7*8 matrix ---by default 7 rows and 8 columns

array([[17, 93, 64,  3, 91, 53, 72, 74],
       [88, 29, 89, 95, 47, 66,  7, 78],
       [53, 11, 25, 34, 42, 76, 54, 82],
       [38, 27, 70, 54, 19, 19,  7, 39],
       [90,  5, 32, 66,  2, 51, 75, 38],
       [42, 31, 93, 84, 83, 98, 87, 39],
       [35, 76, 76, 69, 98, 31, 18, 74]])

In [98]:
"""np.arange(1, 13)
Generates numbers starting from 1 to 12 (stop value 13 is exclusive)

.reshape(3, 4)
Reshapes this 1D array into a 2D array with:
3 rows
4 columns"""

np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [102]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [103]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [104]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [101]:
np.arange(1,13).reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [107]:
a = np.random.randint(10,20,(5,4))
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [108]:
type(a)

numpy.ndarray

In [109]:
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [110]:
a[:]

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [113]:
a[1:3]   #It selects rows from index 1 up to (but not including) index 3

array([[15, 17, 13, 11],
       [16, 13, 10, 16]])

In [111]:
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [112]:
a[1,2]  #Access the element at row index 1 and column index 2 of the array a.

13

In [114]:
print(a[1][2])  # Same as a[1, 2]

13


In [115]:
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [118]:
a[1,2]

13

In [119]:
a[1,-1]

11

In [120]:
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [121]:
a[2:3]

array([[16, 13, 10, 16]])

In [122]:
a[0,-2]

14

In [123]:
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [124]:
a[0,2]

14

In [126]:
a[-5,-3]

10

In [127]:
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

In [128]:
a[-4,2]

13

In [129]:
np.random.randint(10,20,(4,4))

array([[12, 12, 15, 14],
       [11, 19, 18, 19],
       [18, 19, 15, 19],
       [12, 18, 15, 18]])

In [130]:
a

array([[17, 10, 14, 10],
       [15, 17, 13, 11],
       [16, 13, 10, 16],
       [10, 16, 12, 18],
       [19, 11, 10, 15]])

# Operations

In [132]:
a = np.random.randint(10,20,10)    #This code creates a 1D NumPy array containing 10 random integers from 10 (inclusive) to 20 (exclusive).
a

array([13, 15, 10, 18, 10, 13, 16, 18, 16, 14])

In [133]:
a = np.random.randint(10,20,7)
a

array([14, 14, 14, 18, 18, 13, 13])

In [134]:
id(a)

2344522084688

In [135]:
arr

array([0, 1, 2, 3, 4, 5])

In [137]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[69, 42, 47, 67,  0, 34, 49, 61, 41, 75],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31],
       [22, 82,  2, 10, 11, 83, 66, 62, 44, 44],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [71, 72, 77, 70,  8, 49, 42, 32, 72, 55],
       [68,  6, 69, 64, 85, 46, 48, 47, 29, 69],
       [42, 42, 76,  0, 11, 80, 50, 60, 10, 65],
       [54, 94, 90, 24, 90, 36, 19, 88, 63, 75],
       [19, 75, 57, 98, 81,  3, 10, 49, 74,  0],
       [20, 78, 12, 99,  0, 89, 43, 68, 19, 71]])

In [138]:
arr3 = np.random.randint(0,100,(7,5))
arr3

array([[17, 80, 84, 33, 48],
       [89, 37, 38,  6, 68],
       [31, 73,  8, 20, 84],
       [ 3, 68, 68, 75, 73],
       [31, 13, 70, 96, 81],
       [ 9, 18, 89, 50, 82],
       [66, 62, 27, 51, 82]])

In [139]:
arr

array([0, 1, 2, 3, 4, 5])

In [140]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [141]:
arr[:4]

array([0, 1, 2, 3])

In [143]:
arr2[:]

array([[69, 42, 47, 67,  0, 34, 49, 61, 41, 75],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31],
       [22, 82,  2, 10, 11, 83, 66, 62, 44, 44],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [71, 72, 77, 70,  8, 49, 42, 32, 72, 55],
       [68,  6, 69, 64, 85, 46, 48, 47, 29, 69],
       [42, 42, 76,  0, 11, 80, 50, 60, 10, 65],
       [54, 94, 90, 24, 90, 36, 19, 88, 63, 75],
       [19, 75, 57, 98, 81,  3, 10, 49, 74,  0],
       [20, 78, 12, 99,  0, 89, 43, 68, 19, 71]])

In [144]:
arr2[0:5]

array([[69, 42, 47, 67,  0, 34, 49, 61, 41, 75],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31],
       [22, 82,  2, 10, 11, 83, 66, 62, 44, 44],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [71, 72, 77, 70,  8, 49, 42, 32, 72, 55]])

In [146]:
arr3

array([[17, 80, 84, 33, 48],
       [89, 37, 38,  6, 68],
       [31, 73,  8, 20, 84],
       [ 3, 68, 68, 75, 73],
       [31, 13, 70, 96, 81],
       [ 9, 18, 89, 50, 82],
       [66, 62, 27, 51, 82]])

In [147]:
arr3[1,4]

68

In [149]:
arr3[-2,3]

50

In [150]:
arr2

array([[69, 42, 47, 67,  0, 34, 49, 61, 41, 75],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31],
       [22, 82,  2, 10, 11, 83, 66, 62, 44, 44],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [71, 72, 77, 70,  8, 49, 42, 32, 72, 55],
       [68,  6, 69, 64, 85, 46, 48, 47, 29, 69],
       [42, 42, 76,  0, 11, 80, 50, 60, 10, 65],
       [54, 94, 90, 24, 90, 36, 19, 88, 63, 75],
       [19, 75, 57, 98, 81,  3, 10, 49, 74,  0],
       [20, 78, 12, 99,  0, 89, 43, 68, 19, 71]])

In [151]:
arr2[-5,-5]

46

In [152]:
arr2

array([[69, 42, 47, 67,  0, 34, 49, 61, 41, 75],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31],
       [22, 82,  2, 10, 11, 83, 66, 62, 44, 44],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [71, 72, 77, 70,  8, 49, 42, 32, 72, 55],
       [68,  6, 69, 64, 85, 46, 48, 47, 29, 69],
       [42, 42, 76,  0, 11, 80, 50, 60, 10, 65],
       [54, 94, 90, 24, 90, 36, 19, 88, 63, 75],
       [19, 75, 57, 98, 81,  3, 10, 49, 74,  0],
       [20, 78, 12, 99,  0, 89, 43, 68, 19, 71]])

In [156]:
"""This is a NumPy slicing technique used to reverse an array
arr2[start:stop:step]
start → Not specified → Starts from the end (due to negative step).
stop → Not specified → Stops when the array is fully reversed.
step = -1 → Move backward by 1 step → Reverse the array."""

arr2[::-1]

array([[20, 78, 12, 99,  0, 89, 43, 68, 19, 71],
       [19, 75, 57, 98, 81,  3, 10, 49, 74,  0],
       [54, 94, 90, 24, 90, 36, 19, 88, 63, 75],
       [42, 42, 76,  0, 11, 80, 50, 60, 10, 65],
       [68,  6, 69, 64, 85, 46, 48, 47, 29, 69],
       [71, 72, 77, 70,  8, 49, 42, 32, 72, 55],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [22, 82,  2, 10, 11, 83, 66, 62, 44, 44],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31],
       [69, 42, 47, 67,  0, 34, 49, 61, 41, 75]])

In [157]:
arr2

array([[69, 42, 47, 67,  0, 34, 49, 61, 41, 75],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31],
       [22, 82,  2, 10, 11, 83, 66, 62, 44, 44],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [71, 72, 77, 70,  8, 49, 42, 32, 72, 55],
       [68,  6, 69, 64, 85, 46, 48, 47, 29, 69],
       [42, 42, 76,  0, 11, 80, 50, 60, 10, 65],
       [54, 94, 90, 24, 90, 36, 19, 88, 63, 75],
       [19, 75, 57, 98, 81,  3, 10, 49, 74,  0],
       [20, 78, 12, 99,  0, 89, 43, 68, 19, 71]])

In [158]:
arr2[::-2]

array([[20, 78, 12, 99,  0, 89, 43, 68, 19, 71],
       [54, 94, 90, 24, 90, 36, 19, 88, 63, 75],
       [68,  6, 69, 64, 85, 46, 48, 47, 29, 69],
       [47, 25, 29, 94,  6, 15, 58, 24, 86, 76],
       [ 7, 44, 14, 92, 76, 75, 77, 38, 81, 31]])

In [159]:
arr3

array([[17, 80, 84, 33, 48],
       [89, 37, 38,  6, 68],
       [31, 73,  8, 20, 84],
       [ 3, 68, 68, 75, 73],
       [31, 13, 70, 96, 81],
       [ 9, 18, 89, 50, 82],
       [66, 62, 27, 51, 82]])

In [160]:
arr3[::-2]

array([[66, 62, 27, 51, 82],
       [31, 13, 70, 96, 81],
       [31, 73,  8, 20, 84],
       [17, 80, 84, 33, 48]])

In [163]:
arr3

array([[17, 80, 84, 33, 48],
       [89, 37, 38,  6, 68],
       [31, 73,  8, 20, 84],
       [ 3, 68, 68, 75, 73],
       [31, 13, 70, 96, 81],
       [ 9, 18, 89, 50, 82],
       [66, 62, 27, 51, 82]])

In [164]:
arr3[::-3]

array([[66, 62, 27, 51, 82],
       [ 3, 68, 68, 75, 73],
       [17, 80, 84, 33, 48]])

In [165]:
arr3[:-3]

array([[17, 80, 84, 33, 48],
       [89, 37, 38,  6, 68],
       [31, 73,  8, 20, 84],
       [ 3, 68, 68, 75, 73]])

In [166]:
arr

array([0, 1, 2, 3, 4, 5])

In [167]:
arr.max()

5

In [168]:
arr.min()

0

In [169]:
arr

array([0, 1, 2, 3, 4, 5])

In [170]:
arr.mean()

2.5

In [171]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [172]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [174]:
from numpy import *
a = array([1,2,3,4,9])
int(median(a))

3

# # Without work on import* can you please find the median, mode

In [175]:
arr

array([0, 1, 2, 3, 4, 5])

In [176]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [177]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [178]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [179]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [180]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [181]:
arr

array([0, 1, 2, 3, 4, 5])

In [182]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [183]:
arr.reshape(2,3,order='F')  # Print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [184]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [185]:
arr

array([0, 1, 2, 3, 4, 5])

In [186]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [187]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

# Indexing

In [245]:
x = np.arange(0,100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
row = 4
col = 7

In [247]:
row

4

In [248]:
col

7

In [249]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
x[row,col]

47

In [251]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [252]:
x[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [253]:
col = 8

In [254]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [255]:
x[6]    # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [256]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [257]:
# With Slices
"""This is an example of NumPy slicing used to select a specific column from a 2D array or matrix.
The slicing syntax
x[row_indices, column_indices]
: → Selects all rows.    
    col → Selects the column at index col (you provide this value)"""

x[:,col] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [258]:
x[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [259]:
x[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [260]:
x[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [261]:
x[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [262]:
x[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [263]:
x[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [264]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [265]:
row

4

In [266]:
col

8

In [267]:
"""This syntax is used to access a specific element from a 2D NumPy array
x[row_index, column_inde
1 → Selects the second row (index starts from 0).
4 → Selects the fifth column (index 4 → fifth column)."""

x[1,4]

14

In [268]:
"""x[1:4]
This is an example of slicing in NumPy, used to select multiple rows from a 2D array.
In NumPy slicing:
x[start:stop]
start = 1 → Starts from row index 1 (2nd row).
stop = 4 → Stops before row index 4 (excludes index 4).
Selects rows 1, 2, and 3."""

x[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [269]:
x[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [270]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
x[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [272]:
x[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [273]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [274]:
x[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [275]:
x[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [276]:
x[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [277]:
x[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [278]:
x[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [279]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [280]:
x[2:6,2:4]   #2:6 --- only row part ////// 2:4 indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [281]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [282]:
x[1,6]

16

In [283]:
x[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [284]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [285]:
x[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [286]:
x[4:9,3:7]

array([[43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76],
       [83, 84, 85, 86]])

# Masking

In [288]:
mat # We also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [289]:
id(mat)

2344522662128

In [290]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [291]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [292]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [293]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [294]:
mat[mat==50] 

array([50])

In [295]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [296]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [297]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [299]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [300]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [301]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [302]:
a4 = mat[mat==50]
a4

array([50])