# NumPy Buildin Function

# 1. Array Creation Functions

In [3]:
import numpy as np

In [4]:
# Create an array from a list
a = np.array([1,2,3])
print("Array a :",a)

Array a : [1 2 3]


In [5]:
# Create an array with evenly spaced values
b = np.arange(0, 20, 4)  # Values from 0 to 20 with step 3
print("Array b :", b)

Array b : [ 0  4  8 12 16]


In [6]:
# Create an array filled with zeros
x = np.zeros((4,3))   #4*3 array of zeros
print("Array x :",x)

Array x : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Create an array filled with zeros
x = np.zeros((4,3))   #4*3 array of zeros
print("Array x : \n",x)

Array x : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# Create an array filled with ones
e = np.ones((3, 2), dtype=int)  # 3x2 array of ones wit int value
print("Array e:\n", e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [10]:
"""np.eye(N) generates an identity matrix of size N × N.
Identity matrix: A square matrix with:
1’s on the main diagonal (from top-left to bottom-right).
0’s elsewhere."""

# Create an identity matrix
f = np.eye(4)  # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Create an identity matrix
f = np.eye(4, dtype=int)  # 4x4 identity matrix   with int data type
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
g = np.full((3,6),7)    #  	Creates an array filled with a specific value. -----3*6 matrix with 7
print("Array g :\n",g)

Array g :
 [[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [13]:
g = np.full((3,6),7, dtype=float)    # with float value
print("Array g :\n",g)

Array g :
 [[7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7.]]


In [14]:
print(np.linspace(0, 5, 4)) 

[0.         1.66666667 3.33333333 5.        ]


# 2. Array Manipulation Function
Array Manipulation (in NumPy) 

Array manipulation means modifying or changing arrays after they are created to:

 Change their shape or structure
 -----Combine or split them
 -----Change the order of elements
 -----Add or remove elements.

In [15]:
# Reshape an array
#Change the shape/dimensions of an array

a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [16]:
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (3, 1))  # Reshape to 3x1
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[1]
 [2]
 [3]]


In [17]:
a1 = np.arange(1,10)
print("Original Array:",a1)

Original Array: [1 2 3 4 5 6 7 8 9]


In [18]:
reshape = a1.reshape(3,3)
print("Reshape Array:\n",reshape)

Reshape Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# Flatten an array
#Convert multi-dimensional array to 1D.

f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [20]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat_arr = arr.flatten()

print("Original Array:\n", arr)
print("Flattened Array:\n", flat_arr)


Original Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array:
 [1 2 3 4 5 6]


In [21]:
arr = np.arange(1,7)
flat_arr = arr.flatten()

print("Original Array:\n", arr)
print("Flattened Array:\n", flat_arr)


Original Array:
 [1 2 3 4 5 6]
Flattened Array:
 [1 2 3 4 5 6]


In [22]:
# Transpose an array
#Swap rows and columns.

e1 = np.array([[1, 2], [3, 4]])
transpose = np.transpose(e1)  # Transpose the array
print("Transpose array:\n", transpose)

Transpose array:
 [[1 3]
 [2 4]]


In [23]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
transpose_arr = arr.transpose()

print("Original Array:\n", arr)
print("Transposed Array:\n", transpose_arr)

Original Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [24]:
arr = np.arange(1,7)
transpose_arr = arr.transpose()

print("Original Array:\n", arr)
print("Transposed Array:\n", transpose_arr)

Original Array:
 [1 2 3 4 5 6]
Transposed Array:
 [1 2 3 4 5 6]


In [25]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [26]:
# Create four 1D arrays (each with 4 elements)
"""✔ Each 1D array becomes a row in the new matrix.
  ✔ Final matrix has 4 rows and 4 columns → shape (4, 4).
   Arrays must have the same number of columns for vertical stacking."""

a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])
a3 = np.array([9, 10, 11, 12])
a4 = np.array([13, 14, 15, 16])

# Stack vertically to form a 4x4 matrix
stacked_matrix = np.vstack([a1, a2, a3, a4])

print("4x4 Stacked Matrix:\n", stacked_matrix)


4x4 Stacked Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
# Concatenate an array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b))) 

[1 2 3 4 5 6]


# 3. Mathematical Function

In [28]:
# Add two arrays
a = np.array([1, 2, 3, 4])
added = np.add(a, 2)  # Add 2 to each element
print("Added 2 to a:", added)

Added 2 to a: [3 4 5 6]


In [29]:
# Add two arrays
a1 = np.arange(1, 8)
added = np.add(a1, 2)  # Add 2 to each element
print("Added 2 to a1:", added)

Added 2 to a1: [3 4 5 6 7 8 9]


In [30]:
a = np.array([1, 2, 3, 4])
# Add 2 to each element using '+' operator (without np.add)
added = a + 2
print("Added 2 to a:", added)

Added 2 to a: [3 4 5 6]


In [31]:
# Square each element
a = np.array([1, 2, 3, 4])
squared = np.power(a, 2)  # Square each element
print("Squared a:", squared)

Squared a: [ 1  4  9 16]


In [32]:
a = np.array([1, 2, 3, 4])
# Cube each element using '**' operator
cube = a ** 3

print("Cube a:", cube)


Cube a: [ 1  8 27 64]


In [33]:
# Square root of each element
sqrt_val = np.sqrt(a)  # Square root of each element
print("Square root of a:", sqrt_val)

Square root of a: [1.         1.41421356 1.73205081 2.        ]


In [37]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [38]:
# Dot product of two arrays
"""The dot product of two 1D arrays is calculated as:
(1 * 4) + (2 * 5) + (3 * 6) = 4 + 10 + 18 = 32"""

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)   # Dot product of a and g
print("Dot product of a and b:", dot_product)

Dot product of a and b: 32


In [40]:
print(a)
print(a1)

[1 2 3]
[1 2 3 4 5 6 7]


In [42]:
# Dot product of two arrays
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, a1)  # Dot product of a and g
print("Dot product of a and a1:", dot_product)

ValueError: shapes (3,) and (7,) not aligned: 3 (dim 0) != 7 (dim 0)

# 4. Statistical Function
Statistical Functions in NumPy (with Examples)
Statistical functions in NumPy are used to analyze data stored in arrays by calculating statistical measures like:

Sum,
Mean,
Median,
Standard deviation,
Variance,
Min & Max,
Percentile, etc.

In [43]:
"""np.mean() calculates the mean (average) of array elements.

Formula for Mean:
Mean = (Sum of all elements) / (Number of elements)"""

s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [45]:
"""Standard Deviation of an Array in NumPy (with Explanation & Example)

What is Standard Deviation?
Standard Deviation (SD) is a measure of how spread out the numbers are in a dataset.
It tells you how much the numbers differ from the mean.
Lower SD → values are close to the mean
Higher SD → values are more spread out.
"""

arr = np.array([10, 20, 30, 40, 50])
std_dev = np.std(arr)
print("Array:", arr)
print("Standard Deviation:", std_dev)

Array: [10 20 30 40 50]
Standard Deviation: 14.142135623730951


In [46]:
# To find the minimum element of an array in NumPy, you can use the np.min() function or the .min() method.
# # Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [47]:
arr = np.array([10, 25, 3, 40, 18])

# Method 1: Using np.min()
min_element = np.min(arr)

# Method 2: Using array method
min_element2 = arr.min()

print("Minimum element (np.min()):", min_element)
print("Minimum element (array.min()):", min_element2)


Minimum element (np.min()): 3
Minimum element (array.min()): 3


In [50]:
# Creating a 2D array
# Minimum per Column in 2D Array 

arr = np.array([[10, 20, 5],
                [4, 15, 30],
                [25, 8, 12]])

print("Original 2D Array:\n", arr)

# Find minimum element in each column (axis=0 → column-wise)
min_per_column = np.min(arr, axis=0)
print("Minimum element per column:", min_per_column)

Original 2D Array:
 [[10 20  5]
 [ 4 15 30]
 [25  8 12]]
Minimum element per column: [4 8 5]


In [51]:
# Minimum per Row in 2D Array

arr = np.array([[10, 20, 5],
                [4, 15, 30],
                [25, 8, 12]])

print("Original 2D Array:\n", arr)

# Find minimum element in each column (axis=0 → column-wise)
min_per_row = np.min(arr, axis=1)
print("Minimum element per column:", min_per_row)

Original 2D Array:
 [[10 20  5]
 [ 4 15 30]
 [25  8 12]]
Minimum element per column: [5 4 8]


In [53]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


In [52]:
# Maximum element in the array
arr = np.array([10, 25, 3, 40, 18])

# Method 1: Using np.max()
max_element = np.max(arr)

# Method 2: Using array method
max_element2 = arr.max()

print("Maximum element (np.max()):", max_element)
print("Maximum element (array.max()):", max_element2)


Maximum element (np.max()): 40
Maximum element (array.max()): 40


In [55]:
arr = np.arange(1,7)
print(arr)

[1 2 3 4 5 6]


In [62]:
reshape=arr.reshape(2,3)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [63]:
print("Maximum per column:", np.max(reshape, axis=0))  
print("Maximum per row:", np.max(reshape, axis=1))

Maximum per column: [4 5 6]
Maximum per row: [3 6]


In [64]:
arr = np.arange(1, 7)
reshape = arr.reshape(2, 3)
print(reshape)
print("Maximum per column:", np.max(reshape, axis=0))  # Column-wise max
print("Maximum per row:", np.max(reshape, axis=1))     # Row-wise max


[[1 2 3]
 [4 5 6]]
Maximum per column: [4 5 6]
Maximum per row: [3 6]


# 5. Linear Algebra Function

In [67]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


In [68]:
# matrix.T gives the transpose of the matrix.
# rows become column and column becomes row

matrix = np.array([[1, 2],
                   [3, 4]])

print("Original Matrix:\n", matrix)
transpose = matrix.T
print("\nTranspose of the Matrix:\n", transpose)

Original Matrix:
 [[1 2]
 [3 4]]

Transpose of the Matrix:
 [[1 3]
 [2 4]]


#  6.Random Sampling Function

In [69]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.91163813 0.15226855 0.90617506]


In [70]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3,2)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [[0.72263567 0.36368077]
 [0.60673091 0.58502355]
 [0.11249554 0.42246928]]


In [71]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [72]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [73]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7. Boolean & Logical Functions

In [74]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [75]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [76]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [77]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


# 8. Set Operations

In [78]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [79]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Function

In [80]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


#  10. Other Function

In [81]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [82]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [ ]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)